#
# Module manifest
#
# Generated by: Ronny Polley
#

@{
    RootModule = 'posh-sdk.psm1'

    ModuleVersion = '2.0.0'

    #GUID = ""

    Author = 'Ronny Polley'

    Description = 'Powershell module for SDKMan! (www.sdkman.io)'

    PowerShellVersion = '5.0'


}

