# 
# Module manifest
# 
# Generated by: Ronny Polley
#

@{
    RootModule = 'posh-sdk.psm1'

    ModuleVersion = '2.0.0'

    GUID = "564414f7-a83e-4f90-85b7-a1affca03d50"

    Author = 'Ronny Polley'

    Description = 'Powershell module for SDKMan! (www.sdkman.io)'

    PowerShellVersion = '5.0'

    
}
