name: 🕵🏼 Sonarqube Scan
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Run Pester tests (PowerShell)
        run: |
          Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
          Install-Module -Name Pester -RequiredVersion 5.7.1 -Confirm:$false -Force
          $pesterConfig = New-PesterConfiguration
          $pesterConfig.CodeCoverage.Enabled = $true
          $pesterConfig.CodeCoverage.Path="..\PSSDKMan\"
          $pesterConfig.TestResult.Enabled = $true
          Set-Location -Path .\Tests\
          Invoke-Pester -Configuration $pesterConfig
          if ($Error[0].Fullyqualifiederrorid -eq 'PesterAssertionFailed') {exit 1}
        shell: powershell
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
